### PR TITLE
Bug fix: first value row is skipped

### PR DESCRIPTION
**Pull request by eladb**
Since `nextObject` is initially set to `nil`, the first value values
set are set on a `nil` dictionary and hence skipped.

### CODE REVIEW

**Comment by pyro2927** [comment]
Thanks!

**Comment by eladb** [comment]
:+1: Let me know when you are bumping the pod, so we can point to the new
version.

**Comment by pyro2927** [comment]
Here ya go: c6918a81ac7e9734b3a63ff16e484dbd6f0a8537. You should just be able to `pod update` since the podspec in master is pointing to 0.1.1 now.

**Comment by eladb** [comment]
Thanks!

**Comment by genadyo** [comment]
Can you please push to CocoaPods/Specs too?

**Comment by pyro2927** [comment]
PR submitted: https://github.com/CocoaPods/Specs/pull/9347

**Pull request merged**
